[package]
name = "my_rust_egui_app"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.22"
egui = "0.22"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

chrono = "0.4"
